### PR TITLE
WIP: add unit and integration tests; fix html/thymeleaf

### LINKED ISSUE #2: Fix: HTML/Thymeleaf, more test
1. Make HTML and Thymeleaf work for currently implemented logic:
  - player registration/retrieval
  - match creation/retrieval
  - exception handling (display intercepted exception using `@ExceptionHandler`)
[nit]: don't spend too much effort on the UI for now, It'll change soon with new features

2. Add missing tests to achieve at least 90% coverage.

### PR DESCRIPTION
**Pull request by mykola-yefremov**

### CODE REVIEW

File: src/test/unit/java/com/emt/service/PlayerServiceTest.java [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+  @Mock private PlayerMapper playerMapper;
+  @InjectMocks private PlayerService playerService;
+
+  @BeforeEach
+  void setUp() {
+    MockitoAnnotations.openMocks(this);
+  }
+
+  @Test
+  void createPlayer_ShouldCreateNewPlayer_WhenPlayerDoesNotExist() {
```
Comment (chudnovskyi) [inline src/test/unit/java/com/emt/service/PlayerServiceTest.java:36]: nit: `apiUnderTesting_conditions_expectedBehaviour/Outcome`
`createPlayer_WhenPlayerDoesNotExist_ShouldCreateNewPlayer`

File: src/test/unit/java/com/emt/service/MatchServiceTest.java [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+  @Mock private MatchRepository matchRepository;
+
+  @Mock private MatchMapper matchMapper;
+
+  @InjectMocks private MatchService matchService;
+
+  @BeforeEach
+  void setUp() {
+    MockitoAnnotations.openMocks(this);
+  }
```
Comment (chudnovskyi) [inline src/test/unit/java/com/emt/service/MatchServiceTest.java:36]: nit: `@ExtendWith(MockitoExtension.class)`

File: src/test/integration/java/com/emt/controller/MatchControllerIT.java [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+
+    mockMvc
+        .perform(
+            post("/matches/report")
+                .param("winnerId", String.valueOf(winner.playerId()))
+                .param("loserId", String.valueOf(loser.playerId())))
+        .andExpect(status().is3xxRedirection())
+        .andExpect(redirectedUrl("/players"))
+        .andExpect(flash().attribute("message", "Match reported successfully!"));
+  }
```
Comment (chudnovskyi) [inline src/test/integration/java/com/emt/controller/MatchControllerIT.java:49]: Verify that entity is created in the database
OR: you can keep this tests as they are, because they are `controller level`. You can create a separate package with `service level` tests that will check database.

**Review by chudnovskyi — APPROVED** [review]
Don't forget to add IT for service layer on next PR
